server:
  port: 8081

spring:
  application:
    name: UrbanCompany
#  h2:
#    console:
#      enabled: false
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create   # Not a production-level setting

management:
  endpoints:
    web:
      exposure:
        include: "*"      # expose all endpoints
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true



# ===========================
# MySQL Configuration (for production)
# ===========================
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/urban_company_db
#     username: root
#     password: yourpassword
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5Dialect
# logging:
#   level:
#     org.springframework: INFO
#     com.urbancompany: DEBUG
